=begin
#Linode API

#[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

The version of the OpenAPI document: 4.177.1
Contact: support@linode.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module LinodeOpenapiClient
  # An object representing the credit card information you have on file with Linode to make Payments against your Account.
  class AddedPostPaymentMethodData
    # A value from 1-12 representing the expiration month of your credit card.    - 1 = January   - 2 = February   - 3 = March   - Etc.
    attr_accessor :expiry_month

    # Your credit card number. No spaces or hyphens (`-`) allowed.
    attr_accessor :card_number

    # CVV (Card Verification Value) of the credit card, typically found on the back of the card.
    attr_accessor :cvv

    # A four-digit integer representing the expiration year of your credit card.  The combination of `expiry_month` and `expiry_year` must result in a month/year combination of the current month or in the future. An expiration date set in the past is invalid.
    attr_accessor :expiry_year

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'expiry_month' => :'expiry_month',
        :'card_number' => :'card_number',
        :'cvv' => :'cvv',
        :'expiry_year' => :'expiry_year'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'expiry_month' => :'Integer',
        :'card_number' => :'String',
        :'cvv' => :'String',
        :'expiry_year' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LinodeOpenapiClient::AddedPostPaymentMethodData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LinodeOpenapiClient::AddedPostPaymentMethodData`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'expiry_month')
        self.expiry_month = attributes[:'expiry_month']
      else
        self.expiry_month = nil
      end

      if attributes.key?(:'card_number')
        self.card_number = attributes[:'card_number']
      else
        self.card_number = nil
      end

      if attributes.key?(:'cvv')
        self.cvv = attributes[:'cvv']
      else
        self.cvv = nil
      end

      if attributes.key?(:'expiry_year')
        self.expiry_year = attributes[:'expiry_year']
      else
        self.expiry_year = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @expiry_month.nil?
        invalid_properties.push('invalid value for "expiry_month", expiry_month cannot be nil.')
      end

      if @expiry_month > 12
        invalid_properties.push('invalid value for "expiry_month", must be smaller than or equal to 12.')
      end

      if @expiry_month < 1
        invalid_properties.push('invalid value for "expiry_month", must be greater than or equal to 1.')
      end

      if @card_number.nil?
        invalid_properties.push('invalid value for "card_number", card_number cannot be nil.')
      end

      if @card_number.to_s.length > 24
        invalid_properties.push('invalid value for "card_number", the character length must be smaller than or equal to 24.')
      end

      if @card_number.to_s.length < 14
        invalid_properties.push('invalid value for "card_number", the character length must be great than or equal to 14.')
      end

      if @cvv.nil?
        invalid_properties.push('invalid value for "cvv", cvv cannot be nil.')
      end

      if @cvv.to_s.length > 4
        invalid_properties.push('invalid value for "cvv", the character length must be smaller than or equal to 4.')
      end

      if @cvv.to_s.length < 3
        invalid_properties.push('invalid value for "cvv", the character length must be great than or equal to 3.')
      end

      if @expiry_year.nil?
        invalid_properties.push('invalid value for "expiry_year", expiry_year cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @expiry_month.nil?
      return false if @expiry_month > 12
      return false if @expiry_month < 1
      return false if @card_number.nil?
      return false if @card_number.to_s.length > 24
      return false if @card_number.to_s.length < 14
      return false if @cvv.nil?
      return false if @cvv.to_s.length > 4
      return false if @cvv.to_s.length < 3
      return false if @expiry_year.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] expiry_month Value to be assigned
    def expiry_month=(expiry_month)
      if expiry_month.nil?
        fail ArgumentError, 'expiry_month cannot be nil'
      end

      if expiry_month > 12
        fail ArgumentError, 'invalid value for "expiry_month", must be smaller than or equal to 12.'
      end

      if expiry_month < 1
        fail ArgumentError, 'invalid value for "expiry_month", must be greater than or equal to 1.'
      end

      @expiry_month = expiry_month
    end

    # Custom attribute writer method with validation
    # @param [Object] card_number Value to be assigned
    def card_number=(card_number)
      if card_number.nil?
        fail ArgumentError, 'card_number cannot be nil'
      end

      if card_number.to_s.length > 24
        fail ArgumentError, 'invalid value for "card_number", the character length must be smaller than or equal to 24.'
      end

      if card_number.to_s.length < 14
        fail ArgumentError, 'invalid value for "card_number", the character length must be great than or equal to 14.'
      end

      @card_number = card_number
    end

    # Custom attribute writer method with validation
    # @param [Object] cvv Value to be assigned
    def cvv=(cvv)
      if cvv.nil?
        fail ArgumentError, 'cvv cannot be nil'
      end

      if cvv.to_s.length > 4
        fail ArgumentError, 'invalid value for "cvv", the character length must be smaller than or equal to 4.'
      end

      if cvv.to_s.length < 3
        fail ArgumentError, 'invalid value for "cvv", the character length must be great than or equal to 3.'
      end

      @cvv = cvv
    end

    # Custom attribute writer method with validation
    # @param [Object] expiry_year Value to be assigned
    def expiry_year=(expiry_year)
      if expiry_year.nil?
        fail ArgumentError, 'expiry_year cannot be nil'
      end

      @expiry_year = expiry_year
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          expiry_month == o.expiry_month &&
          card_number == o.card_number &&
          cvv == o.cvv &&
          expiry_year == o.expiry_year
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [expiry_month, card_number, cvv, expiry_year].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = LinodeOpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
