=begin
#Linode API

#[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

The version of the OpenAPI document: 4.177.1
Contact: support@linode.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LinodeOpenapiClient::GetDatabasesType200ResponseEnginesPostgresqlInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LinodeOpenapiClient::GetDatabasesType200ResponseEnginesPostgresqlInner do
  let(:instance) { LinodeOpenapiClient::GetDatabasesType200ResponseEnginesPostgresqlInner.new }

  describe 'test an instance of GetDatabasesType200ResponseEnginesPostgresqlInner' do
    it 'should create an instance of GetDatabasesType200ResponseEnginesPostgresqlInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LinodeOpenapiClient::GetDatabasesType200ResponseEnginesPostgresqlInner)
    end
  end

  describe 'test attribute "quantity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Integer', [1, 2, 3])
      # validator.allowable_values.each do |value|
      #   expect { instance.quantity = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "price"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
