=begin
#Linode API

#[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

The version of the OpenAPI document: 4.177.1
Contact: support@linode.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LinodeOpenapiClient::PutLinodeConfigInterfaceRequestIpv4
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LinodeOpenapiClient::PutLinodeConfigInterfaceRequestIpv4 do
  let(:instance) { LinodeOpenapiClient::PutLinodeConfigInterfaceRequestIpv4.new }

  describe 'test an instance of PutLinodeConfigInterfaceRequestIpv4' do
    it 'should create an instance of PutLinodeConfigInterfaceRequestIpv4' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LinodeOpenapiClient::PutLinodeConfigInterfaceRequestIpv4)
    end
  end

  describe 'test attribute "nat_1_1"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "vpc"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
